CREATE TABLE fu_qa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  que TEXT NOT NULL COMMENT '問題',
  ans TEXT NOT NULL COMMENT '答案',
  num INT DEFAULT 0 COMMENT '排序編號',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
